/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mypuntodeventa;

import Model.Productos;
import ModelClases.TextFieldEvent;
import ModelClases.Ventas;
import java.awt.Color;
import java.util.ArrayList;
import com.mxrck.autocompleter.TextAutoCompleter;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author JOSE
 */
public class Panel_Ventas extends javax.swing.JPanel {

    /**
     * Creates new form Panel_Ventas
     */
    private String accion;
    private int num_registro, pageSize;
    public Ventas ventas;
    DefaultTableModel tablaModeloCLT;
    public  TextAutoCompleter matcher;
    ArrayList<Productos> productos;
    ArrayList<Productos> pr;
    TextFieldEvent event;
    String Datos[];
    public Panel_Ventas() {
        initComponents();
        initComponent2();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jTextField_BClientes = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel_ID_Cliente = new javax.swing.JLabel();
        jLabel_Nombre = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel_Saldo = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        jLabel_Cambio = new javax.swing.JLabel();
        jLabel_CamBio = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField_Pago = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton_Cancelar = new javax.swing.JButton();
        jLabel_Panel2 = new javax.swing.JLabel();
        Descuento = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_VentasTempo = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        Label_ApellidoCliente1 = new javax.swing.JLabel();
        jLabel_Total = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jTextField_CodigoVentas = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel_MVentas = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel_Venta = new javax.swing.JLabel();

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jTextField_BClientes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_BClientesKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_BClientesKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Selecciona Cliente");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 102));
        jLabel3.setText("Nombre: ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 0));
        jLabel2.setText("Cuenta:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 102));
        jLabel4.setText("Id. Cliente:");

        jLabel_ID_Cliente.setText("******");

        jLabel_Nombre.setText("********  ******* *******");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("$");

        jLabel_Saldo.setText("0000.00");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Clientes.png"))); // NOI18N

        jCheckBox1.setText("Crédito ");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel9)
                        .addGap(64, 64, 64)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                        .addComponent(jCheckBox1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(37, 37, 37)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel_Saldo))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_Nombre)
                                    .addComponent(jLabel_ID_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addComponent(jTextField_BClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jCheckBox1))
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addComponent(jTextField_BClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel_ID_Cliente))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel_Nombre))
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Saldo))
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel_Cambio.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        jLabel_Cambio.setForeground(new java.awt.Color(0, 102, 153));
        jLabel_Cambio.setText("$0.00");

        jLabel_CamBio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_CamBio.setForeground(new java.awt.Color(0, 153, 153));
        jLabel_CamBio.setText("Cambio:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Efectivo:");

        jTextField_Pago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_PagoActionPerformed(evt);
            }
        });
        jTextField_Pago.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_PagoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_PagoKeyTyped(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ordering.png"))); // NOI18N
        jButton3.setText("Editar Ventas");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton_Cancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cancelar.png"))); // NOI18N
        jButton_Cancelar.setText("Cancelar");
        jButton_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CancelarActionPerformed(evt);
            }
        });

        jLabel_Panel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_Panel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel_Panel2.setText("jLabel5");

        Descuento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Descuento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Left-12.png"))); // NOI18N
        Descuento.setText("Descuento");
        Descuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DescuentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_CamBio, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_Pago, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jButton_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Descuento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING))))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jLabel_Cambio, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jLabel_Panel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Panel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Descuento, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jButton_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Pago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addComponent(jLabel_CamBio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_Cambio)
                .addGap(16, 16, 16))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jTable_VentasTempo = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        jTable_VentasTempo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable_VentasTempo.setFocusable(false);
        jTable_VentasTempo.getTableHeader().setReorderingAllowed(false);
        jTable_VentasTempo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_VentasTempoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_VentasTempo);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        Label_ApellidoCliente1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Label_ApellidoCliente1.setForeground(new java.awt.Color(153, 0, 0));
        Label_ApellidoCliente1.setText("Total :");

        jLabel_Total.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel_Total.setForeground(new java.awt.Color(0, 102, 153));
        jLabel_Total.setText("00.00");
        jLabel_Total.setToolTipText("");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label_ApellidoCliente1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_Total, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Total)
                    .addComponent(Label_ApellidoCliente1))
                .addGap(14, 14, 14))
        );

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/compras.png"))); // NOI18N
        jButton1.setText("Terminar venta");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 418, Short.MAX_VALUE)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel16.setFont(new java.awt.Font("Arial Black", 1, 25)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 51, 102));
        jLabel16.setText("Ventas");

        jTextField_CodigoVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_CodigoVentasActionPerformed(evt);
            }
        });
        jTextField_CodigoVentas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_CodigoVentasKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_CodigoVentasKeyTyped(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setText("Buscar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel_MVentas.setText("Alertas");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(282, 282, 282)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel_MVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField_CodigoVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)))
                .addGap(22, 22, 22)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_CodigoVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_MVentas)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel6.setForeground(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel11.setText("Número de Venta");

        jLabel_Venta.setBackground(new java.awt.Color(0, 153, 153));
        jLabel_Venta.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel_Venta.setText("N. 000000000");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel_Venta, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_Venta, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(92, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    public void initComponent2(){
        ventas = new Ventas();
        event = new TextFieldEvent();
     matcher = new TextAutoCompleter(jTextField_BClientes, (Object selectedItem) -> {
         String nom = (String)selectedItem;
         ventas.selectCliente(nom, jLabel_ID_Cliente, jLabel_Nombre, jLabel_Saldo);
        });
     
     Datos = new String[2];
     num_registro=0;
     pageSize=10;
     restablecerVentas();
     StartTextFields();
     ventas.searchCliente(jTextField_BClientes, matcher);
     ventas.updateLabel(jLabel_Venta);
    }
    
    private void restablecerVentas(){
        //tab =0;
        accion = "insert";
        ventas.searchVentatemp(jTable_VentasTempo, num_registro, pageSize);
        ventas.importes(jLabel_Total,0);
    }
    
    private void StartTextFields(){
        jTextField_BClientes.setEnabled(false);
        jLabel_MVentas.setVisible(false);
        jLabel_Panel2.setVisible(false);
    }
    private void setFileds(){
        jTextField_Pago.setText("");
        jTextField_Pago.setEnabled(true);
        jLabel_Total.setText("00.00");
        jLabel_Cambio.setText("$0.00");
        jLabel_ID_Cliente.setText("******");
        jLabel_Nombre.setText("********  ******* *******");
        jLabel_Saldo.setText("0000.00");
        jCheckBox1.setEnabled(true);
        jCheckBox1.setSelected(false);
        jTextField_BClientes.setText("");
        jTextField_CodigoVentas.setText("");
    }
    public void setTopLabels(){
        jTextField_BClientes.setText("");
        jLabel_ID_Cliente.setText("******");
        jLabel_Nombre.setText("********  ******* *******");
        jLabel_Saldo.setText("0000.00");
    }
    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        if(jCheckBox1.isSelected()){
            jTextField_BClientes.setEnabled(true);
            jTextField_Pago.setEnabled(false);
        }else{
            jTextField_BClientes.setEnabled(false);
            jTextField_Pago.setEnabled(true);
            setTopLabels();
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jTextField_PagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_PagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_PagoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        if(jCheckBox1.isSelected()){
            if(Double.valueOf(jLabel_Total.getText())!= 0 && !(jLabel_Nombre.getText().equals("********  ******* *******"))){
                Datos[0]=jLabel_ID_Cliente.getText();Datos[1]= jLabel_Nombre.getText();
                int response = JOptionPane.showConfirmDialog(null, "Desea imprmir el ticket", "Confirm",
                                       JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                     if(response == JOptionPane.YES_OPTION)
                        ventas.makeNote(Datos);
                ventas.saveVentas(Double.valueOf(jLabel_Total.getText()),Integer.valueOf(jLabel_ID_Cliente.getText()), 123);
                ventas.cleanTable();
                ventas.searchVentatemp(jTable_VentasTempo, num_registro, pageSize);
                setFileds();
                ventas.updateLabel(jLabel_Venta);
                 
            }else{
                JOptionPane.showMessageDialog(null,"No se puede efetuar la venta sin productos o clientes registrados");
            }
        }else if(Double.valueOf(jLabel_Total.getText())!= 0 && !jTextField_Pago.getText().equals("")){
            double cuenta = Double.valueOf(jLabel_Total.getText()) - Double.valueOf(jTextField_Pago.getText());
            if(cuenta<=0){
                 int response = JOptionPane.showConfirmDialog(null, "Desea imprmir el ticket", "Confirm",
                                   JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                 Datos[0]="Cliente General"; Datos[1]="0000";
                 if(response == JOptionPane.YES_OPTION)
                    ventas.makeNote(Datos);
                ventas.saveVentas(Double.valueOf(jLabel_Total.getText()),2, 123);
                ventas.cleanTable();
                setFileds();
                ventas.searchVentatemp(jTable_VentasTempo, num_registro, pageSize);
                ventas.updateLabel(jLabel_Venta);
            }else{
                JOptionPane.showMessageDialog(null,"El efectivo no es suficiente para terminar la compra");
                jTextField_Pago.requestFocus();
            }
        }else{
            JOptionPane.showMessageDialog(null,"No se puede efetuar la venta sin producto registrados o sin registrar el efectivo");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if(jTextField_CodigoVentas.getText().equals("")){
            jLabel_MVentas.setText("Ingrese el codigo del producto...");
            jLabel_MVentas.setForeground(Color.RED);
            jTextField_CodigoVentas.requestFocus();
        }else {
            pr =  ventas.searchProductos(jTextField_CodigoVentas.getText());
            if(0 < pr.size()){
                ventas.saveAux_Ventas(jTextField_CodigoVentas.getText(),0);
                ventas.searchVentatemp(jTable_VentasTempo, num_registro, pageSize);
                ventas.importes(jLabel_Total,0);
                
            }else{
                jLabel_MVentas.setText("El código del producto no existe");
                jLabel_MVentas.setForeground(Color.RED);
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTable_VentasTempoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_VentasTempoMouseClicked
        if(jTable_VentasTempo.getSelectedRows().length > 0){
            jLabel_Panel2.setVisible(false);
            if(evt.getClickCount()== 2){
                //JOptionPane.showMessageDialog(null, "Hola");
                int filas = jTable_VentasTempo.getSelectedRow();
                String codigo = (String) ventas.getModelo().getValueAt(filas,1);
                System.out.println(ventas.clean((String) ventas.getModelo().getValueAt(filas,5)));
                int  cantidad = Integer.parseInt(ventas.clean((String) ventas.getModelo().getValueAt(filas,5)));
                
                ventas.deleteVenta(codigo,cantidad,9);
                ventas.searchVentatemp(jTable_VentasTempo, num_registro, pageSize);
                ventas.importes(jLabel_Total,0);
            }
        }
    }//GEN-LAST:event_jTable_VentasTempoMouseClicked

    private void jTextField_PagoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_PagoKeyReleased
        ventas.pagosCliente(jTextField_Pago, jLabel_Total, jLabel_Cambio,jLabel_CamBio, 00.00);
    }//GEN-LAST:event_jTextField_PagoKeyReleased

    private void jTextField_CodigoVentasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_CodigoVentasKeyReleased
        jLabel_MVentas.setVisible(false);
        event.numberKeyPress(evt, jTextField_BClientes, 12);
    }//GEN-LAST:event_jTextField_CodigoVentasKeyReleased

    private void jTextField_CodigoVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_CodigoVentasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_CodigoVentasActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String Id_Cliente;
        int number=0;
        
        if(jTable_VentasTempo.getSelectedRows().length == 0){
            jLabel_Panel2.setVisible(true);
            jLabel_Panel2.setText("Seleciona un producto");
        }else{
            
            tablaModeloCLT = ventas.getModelo();
            int filas = jTable_VentasTempo.getSelectedRow();
            Id_Cliente = (String)tablaModeloCLT.getValueAt(filas,1);
            System.out.println(Id_Cliente);
            
            boolean canContinue;
            do {
            String userResponse = JOptionPane.showInputDialog(this, "Agrege la cantidad del producto: ", 0);
            try {
                number = Integer.parseInt(userResponse);
                canContinue = true;
                 ventas.updateProducto(Id_Cliente, number);
                 ventas.searchVentatemp(jTable_VentasTempo, num_registro, pageSize);
                 ventas.importes(jLabel_Total, filas);
            }
            catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Agrega un número valido", "Error", JOptionPane.ERROR_MESSAGE);
                canContinue = false;
            }
        } while (!canContinue);
        }
       
    }//GEN-LAST:event_jButton3ActionPerformed

    private void DescuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DescuentoActionPerformed
        String Id_Cliente;
        double Importe;
        double number;
        
        if(jTable_VentasTempo.getSelectedRows().length == 0){
            jLabel_Panel2.setVisible(true);
            jLabel_Panel2.setText("Seleciona un producto");
        }else{
            tablaModeloCLT = ventas.getModelo();
            int filas = jTable_VentasTempo.getSelectedRow();
            Id_Cliente = (String)tablaModeloCLT.getValueAt(filas,1);
            Importe = Double.parseDouble((String)tablaModeloCLT.getValueAt(filas,6));
            boolean canContinue;
            do {
            String userResponse = JOptionPane.showInputDialog(this, "Ingrese el descuento a realizar: ", 0);
            try {
                number = Double.parseDouble(userResponse);
                if(number < Importe){
                    canContinue = true;
                    ventas.setDescuento(Id_Cliente, number);
                    ventas.searchVentatemp(jTable_VentasTempo, num_registro, pageSize);
                    ventas.importes(jLabel_Total, filas);
                }else{
                    JOptionPane.showMessageDialog(null, "El valor del descuento\n"+"Es mayor que la compra");
                    canContinue=false;
                }
            }
            catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Agrega una cantidad valida", "Error", JOptionPane.ERROR_MESSAGE);
                canContinue = false;
            }
        } while (!canContinue);
            
        }
        
    }//GEN-LAST:event_DescuentoActionPerformed

    private void jButton_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CancelarActionPerformed
        String Id_Producto;
        double number=0;
        tablaModeloCLT = ventas.getModelo();
        int filas = jTable_VentasTempo.getSelectedRow();
        Id_Producto = (String)tablaModeloCLT.getValueAt(filas,1);
        System.out.println(Id_Producto);
        if(jTable_VentasTempo.getSelectedRows().length == 0){
            jLabel_Panel2.setVisible(true);
            jLabel_Panel2.setText("Seleciona un producto");
        }else{
            int response = JOptionPane.showConfirmDialog(null, "¿Desea eliminar la venta?", "Confirm",
                                   JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if(response == JOptionPane.YES_OPTION){
                ventas.deleteProductos(Id_Producto);
                ventas.searchVentatemp(jTable_VentasTempo, num_registro, pageSize);
                ventas.importes(jLabel_Total, filas);  
            }
        }
    }//GEN-LAST:event_jButton_CancelarActionPerformed

    private void jTextField_BClientesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_BClientesKeyReleased
      
    }//GEN-LAST:event_jTextField_BClientesKeyReleased

    private void jTextField_PagoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_PagoKeyTyped
        event.numberDecimalKeyPress(evt, jTextField_Pago);
    }//GEN-LAST:event_jTextField_PagoKeyTyped

    private void jTextField_BClientesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_BClientesKeyTyped
        event.nameKeyPress(evt,jTextField_BClientes,20);
    }//GEN-LAST:event_jTextField_BClientesKeyTyped

    private void jTextField_CodigoVentasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_CodigoVentasKeyTyped
        event.numberKeyPress(evt,jTextField_CodigoVentas , 12);
    }//GEN-LAST:event_jTextField_CodigoVentasKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Descuento;
    private javax.swing.JLabel Label_ApellidoCliente1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton_Cancelar;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_CamBio;
    private javax.swing.JLabel jLabel_Cambio;
    private javax.swing.JLabel jLabel_ID_Cliente;
    private javax.swing.JLabel jLabel_MVentas;
    private javax.swing.JLabel jLabel_Nombre;
    private javax.swing.JLabel jLabel_Panel2;
    private javax.swing.JLabel jLabel_Saldo;
    private javax.swing.JLabel jLabel_Total;
    private javax.swing.JLabel jLabel_Venta;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_VentasTempo;
    private javax.swing.JTextField jTextField_BClientes;
    private javax.swing.JTextField jTextField_CodigoVentas;
    private javax.swing.JTextField jTextField_Pago;
    // End of variables declaration//GEN-END:variables
}
