/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mypuntodeventa;

import ModelClases.Clientes;
import ModelClases.Format;
import ModelClases.TextFieldEvent;
import ModelClases.Ventas;
import com.mxrck.autocompleter.TextAutoCompleter;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JOSE
 */
public class Panel_Clientes extends javax.swing.JPanel {

    /**
     * Creates new form Panel_Clientes
     */
    TextFieldEvent evento;
    private String accion;
    Clientes cliente;
    String [] con_Clientes;
    DefaultTableModel tablaModeloCLT;
    Calendar c;
    Ventas venta;
    //Dia = Integer.toString(c.get(Calendar.DAY_OF_MONTH));
    //Mes = Integer.toString(c.get(Calendar.DAY_OF_MONTH));
    //Ano = Integer.toString(c.get(Calendar.DAY_OF_YEAR));
    //fecha = Dia + "/" + Mes + "/" + Ano;
    ArrayList numCliente;
    TextAutoCompleter matcher;
    double deudaAnterior=0, pago=0, deudaActual;
    int num_registro =0, pageSize=7, maxReg,pageCount, num_pag=0,Id_Cliente;
    double Pagos[] = new double[2];
    String Datos[] = new String[2];
    Format format;
    public Panel_Clientes(TextAutoCompleter autoC) {
        initComponents();
        matcher = autoC;
        initComponents2();
        setters();
        
    }
    
    public void initComponents2(){
        evento = new TextFieldEvent();
        cliente = new Clientes();
        accion = "insert";
        con_Clientes = new String[14];
        c = new GregorianCalendar();
        venta  = new Ventas();
        format = new Format();
        //Cargar datos a la tabla 
        cargarDatos();
        
        //Inicializa los campos bloqueados
        emptyFields(false);
        TextField_ID_Cliente.setEnabled(false);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Cliente_Datos = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Label_Nombre_Cliente = new javax.swing.JLabel();
        TextField_Nombre_Clientes = new javax.swing.JTextField();
        Label_AP_Cliente = new javax.swing.JLabel();
        TextField_AP_Cliente = new javax.swing.JTextField();
        Label_AM_Cliente = new javax.swing.JLabel();
        TextField_AM_Cliente = new javax.swing.JTextField();
        TextField_Tel_Cliente = new javax.swing.JTextField();
        Label_ID_Cliente = new javax.swing.JLabel();
        TextField_ID_Cliente = new javax.swing.JTextField();
        Label_Tel_Cliente = new javax.swing.JLabel();
        Label_Cel_Cliente = new javax.swing.JLabel();
        TextField_Cel_Cliente = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        Label_Tel2_Cliente = new javax.swing.JLabel();
        TextField_Tel2_Cliente = new javax.swing.JTextField();
        jButton_Cliente_Eliminar = new javax.swing.JButton();
        jButton_Cliente_Editar = new javax.swing.JButton();
        jTextField_Cliente_Num = new javax.swing.JTextField();
        TextField_Pago_Cliente = new javax.swing.JTextField();
        Label_Pago_Cliente = new javax.swing.JLabel();
        jButton_Cliente_Guardar = new javax.swing.JButton();
        jRadioButton_Cliente_Pago = new javax.swing.JRadioButton();
        jLabel_Cliente_Ciudad = new javax.swing.JLabel();
        jLabel_Cliente_Calle = new javax.swing.JLabel();
        jTextField_Cliente_Colonia = new javax.swing.JTextField();
        jLabel_Cliente_CP = new javax.swing.JLabel();
        jTextField_Cliente_Calle = new javax.swing.JTextField();
        jTextField_Cliente_Ciudad = new javax.swing.JTextField();
        jTextField_Cliente_CP = new javax.swing.JTextField();
        jLabel_Cliente_Colonia = new javax.swing.JLabel();
        jLabel_Cliente_Num = new javax.swing.JLabel();
        jTextField_Cliente_RFC = new javax.swing.JTextField();
        jLabel_Cliente_RFC = new javax.swing.JLabel();
        jButton_Cliente_Cancelar = new javax.swing.JButton();
        jButton_Cliente_Agregar = new javax.swing.JButton();
        jLabel_Cliente_Pago = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jTextField_Filtrar = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jButton_Siguiente = new javax.swing.JButton();
        jButton_Anterior = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_Clientes = new javax.swing.JTable();
        Button_Ultimo = new javax.swing.JButton();
        Button_Primero = new javax.swing.JButton();
        jLabel_Cliente_Page = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        setPreferredSize(new java.awt.Dimension(1330, 529));

        jPanel_Cliente_Datos.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_Cliente_Datos.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 102, 153));
        jLabel13.setText("Datos del Cliente ");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 102, 153));
        jLabel14.setText("Rellene todos los espacios requeridos:  ");

        Label_Nombre_Cliente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Label_Nombre_Cliente.setText("Nombre(s):");

        TextField_Nombre_Clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_Nombre_ClientesActionPerformed(evt);
            }
        });
        TextField_Nombre_Clientes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextField_Nombre_ClientesKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextField_Nombre_ClientesKeyTyped(evt);
            }
        });

        Label_AP_Cliente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Label_AP_Cliente.setText("Apellido Paterno: ");

        TextField_AP_Cliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextField_AP_ClienteKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextField_AP_ClienteKeyTyped(evt);
            }
        });

        Label_AM_Cliente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Label_AM_Cliente.setText("Apellido Materno: ");

        TextField_AM_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_AM_ClienteActionPerformed(evt);
            }
        });
        TextField_AM_Cliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextField_AM_ClienteKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextField_AM_ClienteKeyTyped(evt);
            }
        });

        TextField_Tel_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_Tel_ClienteActionPerformed(evt);
            }
        });
        TextField_Tel_Cliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextField_Tel_ClienteKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextField_Tel_ClienteKeyTyped(evt);
            }
        });

        Label_ID_Cliente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Label_ID_Cliente.setText("Id. Cliente: ");

        TextField_ID_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_ID_ClienteActionPerformed(evt);
            }
        });
        TextField_ID_Cliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextField_ID_ClienteKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextField_ID_ClienteKeyTyped(evt);
            }
        });

        Label_Tel_Cliente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Label_Tel_Cliente.setText("Teléfono: ");

        Label_Cel_Cliente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Label_Cel_Cliente.setText("Celular:");

        TextField_Cel_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_Cel_ClienteActionPerformed(evt);
            }
        });
        TextField_Cel_Cliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextField_Cel_ClienteKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextField_Cel_ClienteKeyTyped(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        Label_Tel2_Cliente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Label_Tel2_Cliente.setText("*Teléfono 2: ");

        TextField_Tel2_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_Tel2_ClienteActionPerformed(evt);
            }
        });
        TextField_Tel2_Cliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextField_Tel2_ClienteKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextField_Tel2_ClienteKeyTyped(evt);
            }
        });

        jButton_Cliente_Eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eliminar.png"))); // NOI18N
        jButton_Cliente_Eliminar.setText("Eliminar");
        jButton_Cliente_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Cliente_EliminarActionPerformed(evt);
            }
        });

        jButton_Cliente_Editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ordering.png"))); // NOI18N
        jButton_Cliente_Editar.setText("Editar");
        jButton_Cliente_Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Cliente_EditarActionPerformed(evt);
            }
        });

        jTextField_Cliente_Num.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Cliente_NumActionPerformed(evt);
            }
        });
        jTextField_Cliente_Num.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_Cliente_NumKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_Cliente_NumKeyTyped(evt);
            }
        });

        TextField_Pago_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_Pago_ClienteActionPerformed(evt);
            }
        });
        TextField_Pago_Cliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextField_Pago_ClienteKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextField_Pago_ClienteKeyTyped(evt);
            }
        });

        Label_Pago_Cliente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Label_Pago_Cliente.setText("Pago");

        jButton_Cliente_Guardar.setBackground(new java.awt.Color(0, 102, 0));
        jButton_Cliente_Guardar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_Cliente_Guardar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Cliente_Guardar.setText("Guardar");
        jButton_Cliente_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Cliente_GuardarActionPerformed(evt);
            }
        });

        jRadioButton_Cliente_Pago.setBackground(new java.awt.Color(204, 204, 204));
        jRadioButton_Cliente_Pago.setText("Pago");
        jRadioButton_Cliente_Pago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_Cliente_PagoActionPerformed(evt);
            }
        });
        jRadioButton_Cliente_Pago.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jRadioButton_Cliente_PagoKeyReleased(evt);
            }
        });

        jLabel_Cliente_Ciudad.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_Cliente_Ciudad.setText("Ciudad ");

        jLabel_Cliente_Calle.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_Cliente_Calle.setText("Calle");

        jTextField_Cliente_Colonia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_Cliente_ColoniaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_Cliente_ColoniaKeyTyped(evt);
            }
        });

        jLabel_Cliente_CP.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_Cliente_CP.setText("C.P");

        jTextField_Cliente_Calle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_Cliente_CalleKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_Cliente_CalleKeyTyped(evt);
            }
        });

        jTextField_Cliente_Ciudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Cliente_CiudadActionPerformed(evt);
            }
        });
        jTextField_Cliente_Ciudad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_Cliente_CiudadKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_Cliente_CiudadKeyTyped(evt);
            }
        });

        jTextField_Cliente_CP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_Cliente_CPKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_Cliente_CPKeyTyped(evt);
            }
        });

        jLabel_Cliente_Colonia.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_Cliente_Colonia.setText("Colonia");

        jLabel_Cliente_Num.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_Cliente_Num.setText("Num.");

        jTextField_Cliente_RFC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_Cliente_RFCKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_Cliente_RFCKeyTyped(evt);
            }
        });

        jLabel_Cliente_RFC.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_Cliente_RFC.setText("*RFC");

        jButton_Cliente_Cancelar.setBackground(new java.awt.Color(153, 0, 0));
        jButton_Cliente_Cancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_Cliente_Cancelar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Cliente_Cancelar.setText("Cancelar");
        jButton_Cliente_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Cliente_CancelarActionPerformed(evt);
            }
        });

        jButton_Cliente_Agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Agregar.png"))); // NOI18N
        jButton_Cliente_Agregar.setText("Agregar");
        jButton_Cliente_Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Cliente_AgregarActionPerformed(evt);
            }
        });

        jLabel_Cliente_Pago.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_Cliente_Pago.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_Cliente_Pago.setForeground(new java.awt.Color(153, 0, 0));
        jLabel_Cliente_Pago.setText(" ¡ Elije a un cliente !");

        javax.swing.GroupLayout jPanel_Cliente_DatosLayout = new javax.swing.GroupLayout(jPanel_Cliente_Datos);
        jPanel_Cliente_Datos.setLayout(jPanel_Cliente_DatosLayout);
        jPanel_Cliente_DatosLayout.setHorizontalGroup(
            jPanel_Cliente_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Cliente_DatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_Cliente_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_Cliente_DatosLayout.createSequentialGroup()
                        .addGroup(jPanel_Cliente_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_Cliente_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(TextField_Nombre_Clientes, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TextField_Tel_Cliente, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField_Cliente_RFC, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Label_Nombre_Cliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Label_Tel_Cliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextField_Cliente_Colonia, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_Cliente_Colonia, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_Cliente_RFC, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(80, 80, 80)
                        .addGroup(jPanel_Cliente_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_Cliente_CP, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel_Cliente_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(TextField_AP_Cliente)
                                .addComponent(TextField_Cel_Cliente)
                                .addComponent(jTextField_Cliente_CP, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                                .addComponent(Label_AP_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel_Cliente_Calle, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Label_Cel_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField_Cliente_Calle)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                        .addGroup(jPanel_Cliente_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_Cliente_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel_Cliente_Ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TextField_AM_Cliente)
                                .addComponent(TextField_Tel2_Cliente)
                                .addComponent(jTextField_Cliente_Ciudad, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                                .addComponent(Label_Tel2_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel_Cliente_Num, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField_Cliente_Num))
                            .addComponent(Label_AM_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(46, Short.MAX_VALUE))
                    .addGroup(jPanel_Cliente_DatosLayout.createSequentialGroup()
                        .addComponent(jButton_Cliente_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jButton_Cliente_Editar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_Cliente_Agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                        .addComponent(jButton_Cliente_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_Cliente_Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(jPanel_Cliente_DatosLayout.createSequentialGroup()
                        .addGroup(jPanel_Cliente_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_Cliente_DatosLayout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(jPanel_Cliente_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel_Cliente_DatosLayout.createSequentialGroup()
                                        .addComponent(Label_ID_Cliente)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(TextField_ID_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel14)
                                    .addGroup(jPanel_Cliente_DatosLayout.createSequentialGroup()
                                        .addGap(639, 639, 639)
                                        .addGroup(jPanel_Cliente_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel23)
                                            .addComponent(jLabel24)))))
                            .addComponent(Label_Pago_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_Cliente_DatosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_Cliente_Pago, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton_Cliente_Pago, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(131, 131, 131))
            .addGroup(jPanel_Cliente_DatosLayout.createSequentialGroup()
                .addGroup(jPanel_Cliente_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_Cliente_DatosLayout.createSequentialGroup()
                        .addGap(255, 255, 255)
                        .addComponent(jLabel13))
                    .addGroup(jPanel_Cliente_DatosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TextField_Pago_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_Cliente_DatosLayout.setVerticalGroup(
            jPanel_Cliente_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Cliente_DatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addGap(37, 37, 37)
                .addComponent(jLabel14)
                .addGap(1, 1, 1)
                .addGroup(jPanel_Cliente_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton_Cliente_Pago)
                    .addComponent(jLabel_Cliente_Pago))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_Cliente_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_ID_Cliente)
                    .addComponent(TextField_ID_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_Cliente_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Nombre_Cliente)
                    .addComponent(Label_AP_Cliente)
                    .addComponent(Label_AM_Cliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_Cliente_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextField_Nombre_Clientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextField_AP_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextField_AM_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_Cliente_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_Cliente_DatosLayout.createSequentialGroup()
                        .addGroup(jPanel_Cliente_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Label_Cel_Cliente)
                            .addComponent(Label_Tel_Cliente)
                            .addComponent(Label_Tel2_Cliente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_Cliente_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextField_Tel2_Cliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextField_Cel_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_Cliente_DatosLayout.createSequentialGroup()
                        .addComponent(TextField_Tel_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)))
                .addGap(6, 6, 6)
                .addGroup(jPanel_Cliente_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Cliente_Ciudad)
                    .addComponent(jLabel_Cliente_CP)
                    .addComponent(jLabel_Cliente_RFC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_Cliente_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_Cliente_RFC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Cliente_Ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Cliente_CP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_Cliente_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Cliente_Colonia)
                    .addGroup(jPanel_Cliente_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel_Cliente_Calle)
                        .addComponent(jLabel_Cliente_Num)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel_Cliente_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_Cliente_Calle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Cliente_Num, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Cliente_Colonia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_Cliente_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24))
                .addGap(26, 26, 26)
                .addComponent(Label_Pago_Cliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TextField_Pago_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel_Cliente_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Cliente_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Cliente_Editar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Cliente_Agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Cliente_Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Cliente_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 102, 102));
        jLabel26.setText("Clientes");

        jTextField_Filtrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_FiltrarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_FiltrarKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_FiltrarKeyTyped(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 102, 102));
        jLabel29.setText("Buscar");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(jLabel29)
                .addGap(28, 28, 28)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_Filtrar, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel26)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Filtrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jButton_Siguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Right.png"))); // NOI18N
        jButton_Siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SiguienteActionPerformed(evt);
            }
        });

        jButton_Anterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Left.png"))); // NOI18N
        jButton_Anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AnteriorActionPerformed(evt);
            }
        });

        jTable_Clientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id. Cliente ", "Nombre ", "Apellido P.", "Deuda", "null"
            }
        ));
        jTable_Clientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_ClientesMouseClicked(evt);
            }
        });
        jTable_Clientes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable_ClientesKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jTable_Clientes);

        Button_Ultimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Right-12.png"))); // NOI18N
        Button_Ultimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_UltimoActionPerformed(evt);
            }
        });

        Button_Primero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Left-12.png"))); // NOI18N
        Button_Primero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_PrimeroActionPerformed(evt);
            }
        });

        jLabel_Cliente_Page.setText("*/*");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel10Layout.createSequentialGroup()
                            .addGap(117, 117, 117)
                            .addComponent(Button_Primero)
                            .addGap(6, 6, 6)
                            .addComponent(jButton_Anterior, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButton_Siguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(6, 6, 6)
                            .addComponent(Button_Ultimo))
                        .addGroup(jPanel10Layout.createSequentialGroup()
                            .addGap(64, 64, 64)
                            .addComponent(jLabel_Cliente_Page, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_Cliente_Page)
                .addGap(6, 6, 6)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Button_Primero, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Anterior, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Siguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_Ultimo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_Cliente_Datos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel_Cliente_Datos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );
    }// </editor-fold>//GEN-END:initComponents
    //<editor-fold defaultstate="collapsed" desc="Codigo Paginados">
    public void cargarDatos(){
                numCliente = cliente.getClientes();
                cliente.searchCliente(jTable_Clientes,"",num_registro,pageSize);
                maxReg = numCliente.size();
                
        pageCount = (maxReg/ pageSize);
        if((maxReg%pageSize) > 0){
            pageCount += 1;
        }
        jLabel_Cliente_Page.setText("Paginas " + "1" + "/ " + String.valueOf(pageCount));
    }
//</editor-fold>
    private void emptyFields(boolean state){
        TextField_ID_Cliente.setEnabled(!state);
        TextField_Nombre_Clientes.setEnabled(state);
        TextField_AP_Cliente.setEnabled(state);
        TextField_AM_Cliente.setEnabled(state);
        TextField_Tel_Cliente.setEnabled(state);
        TextField_Cel_Cliente.setEnabled(state);
        TextField_Tel2_Cliente.setEnabled(state);
        jTextField_Cliente_Num.setEnabled(state);
        TextField_Pago_Cliente.setEnabled(state);
        jTextField_Cliente_RFC.setEnabled(state);
        jTextField_Cliente_CP.setEnabled(state);
        jTextField_Cliente_Ciudad.setEnabled(state);
        jTextField_Cliente_Colonia.setEnabled(state);
        jTextField_Cliente_Calle.setEnabled(state);
        jTextField_Cliente_Num.setEnabled(state);
    }
    private void emptyStr(){
        TextField_ID_Cliente.setText("");
        TextField_Nombre_Clientes.setText("");
        TextField_AP_Cliente.setText("");
        TextField_AM_Cliente.setText("");
        TextField_Tel_Cliente.setText("");
        TextField_Cel_Cliente.setText("");
        TextField_Tel2_Cliente.setText("");
        jTextField_Cliente_RFC.setText("");
        jTextField_Cliente_CP.setText("");
        jTextField_Cliente_Ciudad.setText("");
        jTextField_Cliente_Colonia.setText("");
        jTextField_Cliente_Calle.setText("");
        jTextField_Cliente_Num.setText("");
        TextField_Pago_Cliente.setText("");
    }
    
    private void enabledButtons(boolean state){
        jButton_Cliente_Cancelar.setEnabled(!state);
        jButton_Cliente_Cancelar.setVisible(!state);
        jButton_Cliente_Guardar.setEnabled(!state);
        jButton_Cliente_Guardar.setVisible(!state);
        jButton_Cliente_Eliminar.setEnabled(state);
        jButton_Cliente_Editar.setEnabled(state);
        jButton_Cliente_Agregar.setEnabled(state);
 
        
    }
    private void setLabels(){
        Label_AP_Cliente.setForeground(new Color(0, 0,0));
        Label_Nombre_Cliente.setForeground(new Color(0,0,0));
        Label_AP_Cliente.setForeground(new Color(0,0,0));
        Label_AM_Cliente.setForeground(new Color(0,0,0));
        Label_Tel_Cliente.setForeground(new Color(0,0,0));
        Label_ID_Cliente.setForeground(new Color(0,0,0));
        Label_Cel_Cliente.setForeground(new Color(0,0,0));
        Label_Tel2_Cliente.setForeground(new Color(0,0,0));
        jLabel_Cliente_RFC.setForeground(new Color(0,0,0));
        jLabel_Cliente_CP.setForeground(new Color(0,0,0));
        jLabel_Cliente_Ciudad.setForeground(new Color(0,0,0));
        jLabel_Cliente_Colonia.setForeground(new Color(0,0,0));
        jLabel_Cliente_Calle.setForeground(new Color(0,0,0));
        jLabel_Cliente_Num.setForeground(new Color(0,0,0));
        Label_Pago_Cliente.setForeground(new Color(0,0,0));
        jLabel_Cliente_Pago.setVisible(false);
        //jRadioButton_Cliente_Pago.setSelected(false);
    }
    
    private void setPaneles(){
        jPanel_Cliente_Datos.setSize(834,510);
    }
    
    private void setters(){
        setPaneles();
        enabledButtons(true);
        setLabels();
    }
   
    
    public void setContTables(){
        num_registro=0;
        num_pag=0;
    }
    
    
    
    private void TextField_Nombre_ClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_Nombre_ClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_Nombre_ClientesActionPerformed

    private void TextField_Nombre_ClientesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_Nombre_ClientesKeyReleased
        if(TextField_Nombre_Clientes.getText().equals("")){
            Label_Nombre_Cliente.setForeground(new Color(0,0,0));
        }else{
            //Label_Nombre_Cliente.setText("Nombre(s)");
            Label_Nombre_Cliente.setForeground(new Color(0, 153,51));
        }
    }//GEN-LAST:event_TextField_Nombre_ClientesKeyReleased

    private void TextField_Nombre_ClientesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_Nombre_ClientesKeyTyped
        evento.nameKeyPress(evt,TextField_Nombre_Clientes,20);
    }//GEN-LAST:event_TextField_Nombre_ClientesKeyTyped

    private void TextField_AP_ClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_AP_ClienteKeyReleased
        if(TextField_AP_Cliente.getText().equals("")){
            Label_AP_Cliente.setForeground(new Color(0,0,0));
        }else{
            Label_AP_Cliente.setForeground(new Color(0, 153,51));
        }
    }//GEN-LAST:event_TextField_AP_ClienteKeyReleased

    private void TextField_AP_ClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_AP_ClienteKeyTyped
        evento.nameKeyPress(evt,TextField_AP_Cliente,20);
    }//GEN-LAST:event_TextField_AP_ClienteKeyTyped

    private void TextField_AM_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_AM_ClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_AM_ClienteActionPerformed

    private void TextField_AM_ClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_AM_ClienteKeyReleased
        if(TextField_AM_Cliente.getText().equals("")){
            Label_AM_Cliente.setForeground(new Color(0,0,0));
        }else{
            Label_AM_Cliente.setForeground(new Color(0, 153,51));
        }
    }//GEN-LAST:event_TextField_AM_ClienteKeyReleased

    private void TextField_AM_ClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_AM_ClienteKeyTyped
        evento.nameKeyPress(evt,TextField_AM_Cliente,20);
    }//GEN-LAST:event_TextField_AM_ClienteKeyTyped

    private void TextField_Tel_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_Tel_ClienteActionPerformed
        
    }//GEN-LAST:event_TextField_Tel_ClienteActionPerformed

    private void TextField_Tel_ClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_Tel_ClienteKeyReleased
        if(TextField_Tel_Cliente.getText().equals("") || TextField_Tel_Cliente.getText().length()<10){
            Label_Tel_Cliente.setForeground(new Color(0,0,0));
        }else if(TextField_Tel_Cliente.getText().length()==10){
            //Label_Nombre_Cliente.setText("Nombre(s)");
            Label_Tel_Cliente.setForeground(new Color(0, 153,51));
        }
    }//GEN-LAST:event_TextField_Tel_ClienteKeyReleased

    private void TextField_Tel_ClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_Tel_ClienteKeyTyped
        evento.numberKeyPress(evt,TextField_Tel_Cliente,10);
    }//GEN-LAST:event_TextField_Tel_ClienteKeyTyped

    private void TextField_ID_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_ID_ClienteActionPerformed

    }//GEN-LAST:event_TextField_ID_ClienteActionPerformed

    private void TextField_ID_ClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_ID_ClienteKeyReleased
        if(TextField_ID_Cliente.getText().equals("")){
            Label_ID_Cliente.setForeground(new Color(0,0,0));
        }else{
            //Label_ID_Cliente.setText("ID");
            Label_ID_Cliente.setForeground(new Color(0, 153,51));
        }
    }//GEN-LAST:event_TextField_ID_ClienteKeyReleased

    private void TextField_ID_ClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_ID_ClienteKeyTyped
        evento.numberKeyPress(evt,TextField_ID_Cliente,5);
    }//GEN-LAST:event_TextField_ID_ClienteKeyTyped

    private void TextField_Cel_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_Cel_ClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_Cel_ClienteActionPerformed

    private void TextField_Cel_ClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_Cel_ClienteKeyReleased
        if(TextField_Cel_Cliente.getText().equals("") || TextField_Cel_Cliente.getText().length()<10 ){
            Label_Cel_Cliente.setForeground(new Color(0,0,0));
        }else if (TextField_Cel_Cliente.getText().length()==10){
            //Label_Nombre_Cliente.setText("Nombre(s)");
            Label_Cel_Cliente.setForeground(new Color(0, 153,51));
        }
    }//GEN-LAST:event_TextField_Cel_ClienteKeyReleased

    private void TextField_Tel2_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_Tel2_ClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_Tel2_ClienteActionPerformed

    private void TextField_Tel2_ClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_Tel2_ClienteKeyReleased
        if(TextField_Tel2_Cliente.getText().equals("") || TextField_Tel2_Cliente.getText().length()<10){
            Label_Tel2_Cliente.setForeground(new Color(0,0,0));
        }else{
            Label_Tel2_Cliente.setForeground(new Color(0, 153,51));
        }
    }//GEN-LAST:event_TextField_Tel2_ClienteKeyReleased

    private void TextField_Tel2_ClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_Tel2_ClienteKeyTyped
        evento.numberKeyPress(evt,TextField_Tel2_Cliente,10);
    }//GEN-LAST:event_TextField_Tel2_ClienteKeyTyped

    private void jButton_Cliente_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Cliente_EliminarActionPerformed
        if(jTable_Clientes.getSelectedRows().length>0){
            int response = JOptionPane.showConfirmDialog(this,"Desea eliminar al cliente", "Confirm",
                                   JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if(response== JOptionPane.YES_OPTION){
                cliente.deleteCliente(Id_Cliente);
                emptyStr();
                setContTables();
                cargarDatos();
            }
        }else{
            JOptionPane.showMessageDialog(null, "Selecciona un cliente");
        }
    }//GEN-LAST:event_jButton_Cliente_EliminarActionPerformed

    private void jTextField_Cliente_NumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Cliente_NumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Cliente_NumActionPerformed

    private void jTextField_Cliente_NumKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_Cliente_NumKeyReleased
        if(jTextField_Cliente_Num.getText().equals("")){
            jLabel_Cliente_Num.setForeground(new Color(102,102,102));
        }else{
            jLabel_Cliente_Num.setForeground(new Color(0, 153,51));
        }
    }//GEN-LAST:event_jTextField_Cliente_NumKeyReleased

    private void jTextField_Cliente_NumKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_Cliente_NumKeyTyped
        evento.numberKeyPress(evt, jTextField_Cliente_Num,6);
    }//GEN-LAST:event_jTextField_Cliente_NumKeyTyped

    private void TextField_Pago_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_Pago_ClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_Pago_ClienteActionPerformed

    private void TextField_Pago_ClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_Pago_ClienteKeyReleased
        if(TextField_Pago_Cliente.getText().equals("")){
             Label_Pago_Cliente.setForeground(new Color(0,0,0));
        }else{
             Label_Pago_Cliente.setForeground(new Color(0, 153,51));
             int filas = jTable_Clientes.getSelectedRow();
             deudaAnterior = Double.valueOf((String)tablaModeloCLT.getValueAt(filas,3));
             pago = Double.parseDouble(TextField_Pago_Cliente.getText());
             deudaActual = deudaAnterior-pago;
             deudaActual = format.decimalFormat(deudaActual);
             System.out.println(deudaActual);
             if(deudaActual<0){
                 deudaActual = 0;
                 JOptionPane.showMessageDialog(null,"El pago es mayor que la deuda");
             }
        }
    }//GEN-LAST:event_TextField_Pago_ClienteKeyReleased

    private void TextField_Pago_ClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_Pago_ClienteKeyTyped
        evento.numberDecimalKeyPress(evt,TextField_Pago_Cliente);
    }//GEN-LAST:event_TextField_Pago_ClienteKeyTyped

    private void jButton_Cliente_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Cliente_GuardarActionPerformed
        if(!jRadioButton_Cliente_Pago.isSelected()){
            guardarCliente();
            venta.updateList(matcher);
        }else{
            guardarPago();
            TextField_Pago_Cliente.setText("");
        }
    }//GEN-LAST:event_jButton_Cliente_GuardarActionPerformed

    private void jRadioButton_Cliente_PagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_Cliente_PagoActionPerformed

       if(jTable_Clientes.getSelectedRows().length == 0){
           jLabel_Cliente_Pago.setVisible(true);
           jRadioButton_Cliente_Pago.setSelected(false);
       }else{
           if(jRadioButton_Cliente_Pago.isSelected()){
                emptyFields(false);
                TextField_Pago_Cliente.setEnabled(true);
                TextField_ID_Cliente.setEnabled(false);
                jTable_Clientes.setEnabled(false);
                enabledButtons(false);
            }else{
               TextField_Pago_Cliente.setEnabled(false);
               jTable_Clientes.setEnabled(true);
               enabledButtons(true);
           }
       } 
    }//GEN-LAST:event_jRadioButton_Cliente_PagoActionPerformed

    private void TextField_Cel_ClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_Cel_ClienteKeyTyped
        evento.numberKeyPress(evt,TextField_Cel_Cliente,10);
    }//GEN-LAST:event_TextField_Cel_ClienteKeyTyped

    private void jTextField_Cliente_CiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Cliente_CiudadActionPerformed
        
    }//GEN-LAST:event_jTextField_Cliente_CiudadActionPerformed

    private void jTextField_Cliente_RFCKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_Cliente_RFCKeyReleased
        if(jTextField_Cliente_RFC.getText().equals("") || jTextField_Cliente_RFC.getText().length()<12){
            jLabel_Cliente_RFC.setForeground(new Color(0,0,0));
        }else{
            jLabel_Cliente_RFC.setForeground(new Color(0,153,51));
        }
    }//GEN-LAST:event_jTextField_Cliente_RFCKeyReleased

    private void jTextField_Cliente_CPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_Cliente_CPKeyReleased
        if(jTextField_Cliente_CP.getText().equals("")|| jTextField_Cliente_CP.getText().length()<5){
            jLabel_Cliente_CP.setForeground(new Color(0,0,0));
        }else{
            //Label_Nombre_Cliente.setText("Nombre(s)");
            jLabel_Cliente_CP.setForeground(new Color(0,153,51));
        }
    }//GEN-LAST:event_jTextField_Cliente_CPKeyReleased

    private void jTextField_Cliente_CiudadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_Cliente_CiudadKeyReleased
        if(jTextField_Cliente_Ciudad.getText().equals("")){
            jLabel_Cliente_Ciudad.setForeground(new Color(0,0,0));
        }else{
            //Label_Nombre_Cliente.setText("Nombre(s)");
            jLabel_Cliente_Ciudad.setForeground(new Color(0,153,51));
        }
    }//GEN-LAST:event_jTextField_Cliente_CiudadKeyReleased

    private void jTextField_Cliente_ColoniaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_Cliente_ColoniaKeyReleased
        if(jTextField_Cliente_Colonia.getText().equals("")){
            jLabel_Cliente_Colonia.setForeground(new Color(0,0,0));
        }else{
            //Label_Nombre_Cliente.setText("Nombre(s)");
            jLabel_Cliente_Colonia.setForeground(new Color(0,153,51));
        }
    }//GEN-LAST:event_jTextField_Cliente_ColoniaKeyReleased

    private void jTextField_Cliente_CalleKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_Cliente_CalleKeyReleased
        if(jTextField_Cliente_Calle.getText().equals("")){
            jLabel_Cliente_Calle.setForeground(new Color(0,0,0));
        }else{
            //Label_Nombre_Cliente.setText("Nombre(s)");
            jLabel_Cliente_Calle.setForeground(new Color(0,153,51));
        }
    }//GEN-LAST:event_jTextField_Cliente_CalleKeyReleased

    private void jTextField_Cliente_RFCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_Cliente_RFCKeyTyped
        evento.text_numKeyPress(evt, jTextField_Cliente_RFC,13);
    }//GEN-LAST:event_jTextField_Cliente_RFCKeyTyped

    private void jTextField_Cliente_CPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_Cliente_CPKeyTyped
        evento.numberKeyPress(evt, jTextField_Cliente_CP,5);
    }//GEN-LAST:event_jTextField_Cliente_CPKeyTyped

    private void jTextField_Cliente_CiudadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_Cliente_CiudadKeyTyped
        evento.nameKeyPress(evt, jTextField_Cliente_Ciudad,20);
    }//GEN-LAST:event_jTextField_Cliente_CiudadKeyTyped

    private void jTextField_Cliente_ColoniaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_Cliente_ColoniaKeyTyped
        evento.name_numKeyPress(evt, jTextField_Cliente_Colonia,20);
    }//GEN-LAST:event_jTextField_Cliente_ColoniaKeyTyped

    private void jTextField_Cliente_CalleKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_Cliente_CalleKeyTyped
        evento.name_numKeyPress(evt, jTextField_Cliente_Calle,20);
    }//GEN-LAST:event_jTextField_Cliente_CalleKeyTyped

    private void jButton_Cliente_AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Cliente_AgregarActionPerformed
        emptyFields(true);
        emptyStr();
        accion = "insert";
        jTable_Clientes.setEnabled(false);
        TextField_Pago_Cliente.setEnabled(false);
        jButton_Cliente_Cancelar.setEnabled(true);
        jButton_Cliente_Cancelar.setVisible(true);
        jButton_Cliente_Guardar.setEnabled(true);
        jButton_Cliente_Guardar.setVisible(true);
        jButton_Cliente_Eliminar.setEnabled(false);
        jButton_Cliente_Editar.setEnabled(false);
        jButton_Cliente_Agregar.setEnabled(false);
        jRadioButton_Cliente_Pago.setEnabled(false);
    }//GEN-LAST:event_jButton_Cliente_AgregarActionPerformed

    private void jButton_Cliente_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Cliente_CancelarActionPerformed
        emptyFields(false);
        emptyStr();
        setLabels();
        jTable_Clientes.setEnabled(true);
        jButton_Cliente_Cancelar.setEnabled(false);
        jButton_Cliente_Cancelar.setVisible(false);
        jButton_Cliente_Guardar.setEnabled(false);
        jButton_Cliente_Guardar.setVisible(false);
        jButton_Cliente_Eliminar.setEnabled(true);
        jButton_Cliente_Editar.setEnabled(true);
        jButton_Cliente_Agregar.setEnabled(true);
        jRadioButton_Cliente_Pago.setEnabled(true);
        jRadioButton_Cliente_Pago.setSelected(false);
        TextField_ID_Cliente.setEnabled(false);
        cargarDatos();
    }//GEN-LAST:event_jButton_Cliente_CancelarActionPerformed

    private void jButton_Cliente_EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Cliente_EditarActionPerformed
        if(jTable_Clientes.getSelectedRows().length > 0){
            emptyFields(true);
            jTable_Clientes.setEnabled(false);
            TextField_Pago_Cliente.setEnabled(false);
            TextField_ID_Cliente.setEnabled(false);
            jButton_Cliente_Cancelar.setEnabled(true);
            jButton_Cliente_Cancelar.setVisible(true);
            jButton_Cliente_Guardar.setEnabled(true);
            jButton_Cliente_Guardar.setVisible(true);
            jButton_Cliente_Eliminar.setEnabled(false);
            jButton_Cliente_Editar.setEnabled(false);
            jButton_Cliente_Agregar.setEnabled(false);
            jRadioButton_Cliente_Pago.setEnabled(false);
        }else{
            JOptionPane.showMessageDialog(null,"Elija a un cliente");
        }
        
    }//GEN-LAST:event_jButton_Cliente_EditarActionPerformed

    private void jRadioButton_Cliente_PagoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jRadioButton_Cliente_PagoKeyReleased
        
    }//GEN-LAST:event_jRadioButton_Cliente_PagoKeyReleased

    private void jTextField_FiltrarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_FiltrarKeyTyped

    }//GEN-LAST:event_jTextField_FiltrarKeyTyped

    private void jTextField_FiltrarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_FiltrarKeyReleased

        System.out.println(num_pag);
        cliente.searchCliente(jTable_Clientes, jTextField_Filtrar.getText(),0, pageSize);

    }//GEN-LAST:event_jTextField_FiltrarKeyReleased

    private void jTextField_FiltrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_FiltrarKeyPressed

    }//GEN-LAST:event_jTextField_FiltrarKeyPressed

    private void Button_PrimeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_PrimeroActionPerformed
        num_pag = 0;
        jLabel_Cliente_Page.setText("Paginas " + "1" + "/ " + String.valueOf(pageCount));
        cliente.searchCliente(jTable_Clientes,"",num_pag,pageSize);
    }//GEN-LAST:event_Button_PrimeroActionPerformed

    private void Button_UltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_UltimoActionPerformed
        num_pag = pageCount-1;
        num_registro = pageSize * num_pag;
        jLabel_Cliente_Page.setText("Paginas " + String.valueOf(num_pag) + "/ " +
            String.valueOf(pageCount));
        cliente.searchCliente(jTable_Clientes,"",num_registro,pageSize);
        num_pag = pageCount;
    }//GEN-LAST:event_Button_UltimoActionPerformed

    private void jTable_ClientesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable_ClientesKeyReleased
        if(jTable_Clientes.getSelectedRows().length > 0){
            datosClientes();
        }
    }//GEN-LAST:event_jTable_ClientesKeyReleased

    private void jTable_ClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_ClientesMouseClicked
        if(jTable_Clientes.getSelectedRows().length > 0){
            datosClientes();
            jLabel_Cliente_Pago.setVisible(false);
        }
    }//GEN-LAST:event_jTable_ClientesMouseClicked

    private void jButton_AnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AnteriorActionPerformed
        if(pageCount != 1){
            if(num_pag >0){
                if(pageCount == num_pag){
                    num_pag -= 1;
                }
                jLabel_Cliente_Page.setText("Paginas " + String.valueOf(num_pag) + "/ " + String.valueOf(pageCount));
                num_pag-=1;
                num_registro = pageSize * num_pag;
                cliente.searchCliente(jTable_Clientes,"",num_registro,pageSize);
            }
        }
    }//GEN-LAST:event_jButton_AnteriorActionPerformed

    private void jButton_SiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SiguienteActionPerformed
        if(pageCount != 1){
            if(num_pag<pageCount){
                if(num_pag == 0){
                    num_pag += 1;
                }
                num_registro = pageSize * num_pag;
                cliente.searchCliente(jTable_Clientes,"",num_registro,pageSize);
                num_pag+=1;
                jLabel_Cliente_Page.setText("Paginas " + String.valueOf(num_pag) + "/ " + String.valueOf(pageCount));
            }
        }
    }//GEN-LAST:event_jButton_SiguienteActionPerformed
    private void datosClientes(){
        accion = "update";
        tablaModeloCLT = cliente.getModelo();
        int filas = jTable_Clientes.getSelectedRow();
        Id_Cliente = Integer.valueOf((String)tablaModeloCLT.getValueAt(filas,0));
        con_Clientes = cliente.consultCliente(Id_Cliente);
        TextField_ID_Cliente.setText(con_Clientes[0]);
        TextField_Nombre_Clientes.setText(con_Clientes[1]);
        TextField_AP_Cliente.setText(con_Clientes[2]);
        TextField_AM_Cliente.setText(con_Clientes[3]);
        TextField_Tel_Cliente.setText(con_Clientes[4]);
        TextField_Cel_Cliente.setText(con_Clientes[5]);
        TextField_Tel2_Cliente.setText(con_Clientes[6]);
        jTextField_Cliente_RFC.setText(con_Clientes[8]);
        jTextField_Cliente_CP.setText(con_Clientes[9]);
        jTextField_Cliente_Ciudad.setText(con_Clientes[10]);
        jTextField_Cliente_Colonia.setText(con_Clientes[11]);
        jTextField_Cliente_Calle.setText(con_Clientes[12]);
        jTextField_Cliente_Num.setText(con_Clientes[13]);
        
    }
    
    private void guardarCliente(){
        if(false){
        }else{
            if(TextField_Nombre_Clientes.getText().equals("")){
                Label_Nombre_Cliente.setText("Ingrese Nombre");
                Label_Nombre_Cliente.setForeground(Color.RED);
                TextField_Nombre_Clientes.requestFocus();
            }else{
                if(TextField_AP_Cliente.getText().equals("")){
                    Label_AP_Cliente.setText("Ingrese Cliente");
                    Label_AP_Cliente.setForeground(Color.RED);
                    TextField_AP_Cliente.requestFocus();
                }else{
                    if(TextField_AM_Cliente.getText().equals("")){
                        Label_AM_Cliente.setText("Ingrese Apellido Materno");
                        Label_AM_Cliente.setForeground(Color.RED);
                        TextField_AM_Cliente.requestFocus();
                    }else{
                        if(TextField_Tel_Cliente.getText().equals("") || TextField_Tel_Cliente.getText().length()<10){
                            Label_Tel_Cliente.setText("Ingrese Telefono Valido");
                            Label_Tel_Cliente.setForeground(Color.RED);
                            TextField_AM_Cliente.requestFocus();
                        }else{
                            if(TextField_Cel_Cliente.getText().equals("")){
                                Label_Cel_Cliente.setText("Ingrese Celular");
                                Label_Cel_Cliente.setForeground(Color.RED);
                                TextField_Cel_Cliente.requestFocus();
                            }else{
                                if(false){
                                }else{
                                    if(jTextField_Cliente_CP.getText().equals("")){
                                        jLabel_Cliente_CP.setText("Ingrese CP");
                                        jLabel_Cliente_CP.setForeground(Color.RED);
                                        jTextField_Cliente_CP.requestFocus();
                                    }else{
                                        if(jTextField_Cliente_Ciudad.getText().equals("")){
                                            jLabel_Cliente_Ciudad.setText("Ingrese Ciudad");
                                            jLabel_Cliente_Ciudad.setForeground(Color.RED);
                                            jTextField_Cliente_Ciudad.requestFocus();
                                        }else{
                                            if(jTextField_Cliente_Colonia.getText().equals("")){
                                                jLabel_Cliente_Colonia.setText("Ingrese Colonia");
                                                jLabel_Cliente_Colonia.setForeground(Color.RED);
                                                jTextField_Cliente_Colonia.requestFocus();
                                            }else{
                                                   if(jTextField_Cliente_Calle.getText().equals("")){
                                                        jLabel_Cliente_Calle.setText("Ingrese Calle");
                                                        jLabel_Cliente_Calle.setForeground(Color.RED);
                                                        jTextField_Cliente_Calle.requestFocus();
                                                    }else{
                                                            if(jTextField_Cliente_Num.getText().equals("")){
                                                                jLabel_Cliente_Num.setText("Ingrese Numero");
                                                                jLabel_Cliente_Num.setForeground(Color.RED);
                                                                jTextField_Cliente_Num.requestFocus();
                                                            }else{
                                                                         //int ID = Integer.parseInt(TextField_ID_Cliente.getText());
                                                                        String Nombre  = TextField_Nombre_Clientes.getText();
                                                                        String ApellidoPat = TextField_AP_Cliente.getText();
                                                                        String ApellidoMat = TextField_AM_Cliente.getText();
                                                                        String TelefonoCliente = TextField_Tel_Cliente.getText();
                                                                        String Celular = TextField_Cel_Cliente.getText();
                                                                        String Tel2 = TextField_Tel2_Cliente.getText();
                                                                        String RFC = jTextField_Cliente_RFC.getText();
                                                                        String CP = jTextField_Cliente_CP.getText();
                                                                        String Ciudad = jTextField_Cliente_Ciudad.getText();
                                                                        String Colonia = jTextField_Cliente_Colonia.getText();
                                                                        String Calle = jTextField_Cliente_Calle.getText();
                                                                        String Numero_Dom = jTextField_Cliente_Num.getText();
                                                                    switch(accion){
                                                                        case "insert" :
                                                                            
                                                                                cliente.insertCliente(Nombre, ApellidoPat, ApellidoMat, TelefonoCliente, Celular, 
                                                                                Tel2, 150.90, RFC,CP,Ciudad,Colonia,Calle,Numero_Dom);
                                                                                    
                                                                                    JOptionPane.showMessageDialog(this, "Cliente agregado exitosamente");
                                                                                    emptyStr();
                                                                                    setLabels();
                                                                            
                                                                            break;
                                                                        case "update":
                                                                                cliente.updateCliente(Id_Cliente, Nombre, ApellidoPat, ApellidoMat, Tel2, Celular, Tel2, RFC, CP, Ciudad, Colonia, Calle, Numero_Dom);
                                                                                JOptionPane.showMessageDialog(this, "Cliente actualizado exitosamente");
                                                                                //emptyStr();
                                                                                break;
                                                              
                                                                    }
                                                                    
                                        
                                                            }
                                                            
                                                    }
                                            }
                                        
                                        }
                                        
                                    }
                
                                }
                
                            }
                
                        }
                
                    }
                }
                
            }
        }
    }
    
        public void guardarPago(){
            if(TextField_Pago_Cliente.getText().equals("")){
                Label_Pago_Cliente.setText("Ingrese el pago");
                Label_Pago_Cliente.setForeground(Color.RED);
                TextField_Pago_Cliente.requestFocus();
            }else{
                try{
                cliente.updateReportes(Id_Cliente,123,"05/10/10", pago,deudaAnterior,deudaActual);
                cliente.updatePago(deudaActual,Id_Cliente);
                Pagos[0]=deudaAnterior;Pagos[1] = pago;
                Datos[0]=TextField_ID_Cliente.getText();Datos[1]=TextField_Nombre_Clientes.getText()+" "+TextField_AP_Cliente.getText();
                    System.out.println(TextField_Nombre_Clientes.getText()+" "+TextField_AP_Cliente.getText());
                int response = JOptionPane.showConfirmDialog(this,"Desea imprimir el recibo", "Confirm",
                                   JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if(response== JOptionPane.YES_OPTION)
                    cliente.makeNote(Pagos,Datos);
                }catch(Exception ex){
                        
                }
            }
        }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Primero;
    private javax.swing.JButton Button_Ultimo;
    private javax.swing.JLabel Label_AM_Cliente;
    private javax.swing.JLabel Label_AP_Cliente;
    private javax.swing.JLabel Label_Cel_Cliente;
    private javax.swing.JLabel Label_ID_Cliente;
    private javax.swing.JLabel Label_Nombre_Cliente;
    private javax.swing.JLabel Label_Pago_Cliente;
    private javax.swing.JLabel Label_Tel2_Cliente;
    private javax.swing.JLabel Label_Tel_Cliente;
    private javax.swing.JTextField TextField_AM_Cliente;
    private javax.swing.JTextField TextField_AP_Cliente;
    private javax.swing.JTextField TextField_Cel_Cliente;
    private javax.swing.JTextField TextField_ID_Cliente;
    private javax.swing.JTextField TextField_Nombre_Clientes;
    private javax.swing.JTextField TextField_Pago_Cliente;
    private javax.swing.JTextField TextField_Tel2_Cliente;
    private javax.swing.JTextField TextField_Tel_Cliente;
    private javax.swing.JButton jButton_Anterior;
    private javax.swing.JButton jButton_Cliente_Agregar;
    private javax.swing.JButton jButton_Cliente_Cancelar;
    private javax.swing.JButton jButton_Cliente_Editar;
    private javax.swing.JButton jButton_Cliente_Eliminar;
    private javax.swing.JButton jButton_Cliente_Guardar;
    private javax.swing.JButton jButton_Siguiente;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel_Cliente_CP;
    private javax.swing.JLabel jLabel_Cliente_Calle;
    private javax.swing.JLabel jLabel_Cliente_Ciudad;
    private javax.swing.JLabel jLabel_Cliente_Colonia;
    private javax.swing.JLabel jLabel_Cliente_Num;
    private javax.swing.JLabel jLabel_Cliente_Page;
    private javax.swing.JLabel jLabel_Cliente_Pago;
    private javax.swing.JLabel jLabel_Cliente_RFC;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel_Cliente_Datos;
    private javax.swing.JRadioButton jRadioButton_Cliente_Pago;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable_Clientes;
    private javax.swing.JTextField jTextField_Cliente_CP;
    private javax.swing.JTextField jTextField_Cliente_Calle;
    private javax.swing.JTextField jTextField_Cliente_Ciudad;
    private javax.swing.JTextField jTextField_Cliente_Colonia;
    private javax.swing.JTextField jTextField_Cliente_Num;
    private javax.swing.JTextField jTextField_Cliente_RFC;
    private javax.swing.JTextField jTextField_Filtrar;
    // End of variables declaration//GEN-END:variables
}
