/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mypuntodeventa;

import Connection.Conexion;
import ModelClases.Clientes;
import ModelClases.TextFieldEvent;
import com.mxrck.autocompleter.TextAutoCompleter;
import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author JOSE
 */
public class View extends javax.swing.JFrame {

    /**
     * Creates new form View
     */
    private String accion = "insert";
    Clientes cliente = new Clientes();
    TextFieldEvent evento = new TextFieldEvent();
    
    Panel_Clientes p_c;
    Panel_Ventas p_v;
    Panel_Compras p_compras;
    int tab;
   
    public View() {
        initComponents();
        initComponents2();
        cliente.consultCliente(5);
        new Conexion();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void initComponents2(){
        p_v = new Panel_Ventas();
        p_compras = new Panel_Compras();
        p_c = new Panel_Clientes(p_v.matcher);
        jPanel_Compras.setLayout(new BorderLayout());
        jPanel_Compras.add(p_compras, BorderLayout.CENTER);
        jPanel_Ventas.setLayout(new BorderLayout());
        jPanel_Ventas.add(p_v, BorderLayout.CENTER);
        //jPanel_Proveedores.setLayout(new BorderLayout(5,5));
        //jPanel_Proveedores.add(prov, BorderLayout.CENTER);
        jPanel_Cliente.setLayout(new BorderLayout());
        jPanel_Cliente.add(p_c, BorderLayout.CENTER);
        
        
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel_Cliente = new javax.swing.JPanel();
        jPanel_C = new javax.swing.JPanel();
        jPanel_Proveedores = new javax.swing.JPanel();
        jPanel_Productos = new javax.swing.JPanel();
        jPanel_Ventas = new javax.swing.JPanel();
        jPanel_Compras = new javax.swing.JPanel();
        Button_Clientes = new javax.swing.JButton();
        Button_Ventas = new javax.swing.JButton();
        Button_Compras = new javax.swing.JButton();
        Button_Productos = new javax.swing.JButton();
        Button_Config = new javax.swing.JButton();
        Button_Proveedores = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setPreferredSize(new java.awt.Dimension(1366, 750));

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);

        jPanel_Cliente.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel_ClienteLayout = new javax.swing.GroupLayout(jPanel_Cliente);
        jPanel_Cliente.setLayout(jPanel_ClienteLayout);
        jPanel_ClienteLayout.setHorizontalGroup(
            jPanel_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1301, Short.MAX_VALUE)
        );
        jPanel_ClienteLayout.setVerticalGroup(
            jPanel_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 583, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab1", jPanel_Cliente);

        jPanel_C.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel_CLayout = new javax.swing.GroupLayout(jPanel_C);
        jPanel_C.setLayout(jPanel_CLayout);
        jPanel_CLayout.setHorizontalGroup(
            jPanel_CLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1301, Short.MAX_VALUE)
        );
        jPanel_CLayout.setVerticalGroup(
            jPanel_CLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 583, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab2", jPanel_C);

        javax.swing.GroupLayout jPanel_ProveedoresLayout = new javax.swing.GroupLayout(jPanel_Proveedores);
        jPanel_Proveedores.setLayout(jPanel_ProveedoresLayout);
        jPanel_ProveedoresLayout.setHorizontalGroup(
            jPanel_ProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1301, Short.MAX_VALUE)
        );
        jPanel_ProveedoresLayout.setVerticalGroup(
            jPanel_ProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 583, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab3", jPanel_Proveedores);

        javax.swing.GroupLayout jPanel_ProductosLayout = new javax.swing.GroupLayout(jPanel_Productos);
        jPanel_Productos.setLayout(jPanel_ProductosLayout);
        jPanel_ProductosLayout.setHorizontalGroup(
            jPanel_ProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1301, Short.MAX_VALUE)
        );
        jPanel_ProductosLayout.setVerticalGroup(
            jPanel_ProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 583, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab4", jPanel_Productos);

        javax.swing.GroupLayout jPanel_VentasLayout = new javax.swing.GroupLayout(jPanel_Ventas);
        jPanel_Ventas.setLayout(jPanel_VentasLayout);
        jPanel_VentasLayout.setHorizontalGroup(
            jPanel_VentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1301, Short.MAX_VALUE)
        );
        jPanel_VentasLayout.setVerticalGroup(
            jPanel_VentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 583, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab5", jPanel_Ventas);

        jPanel_Compras.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel_ComprasLayout = new javax.swing.GroupLayout(jPanel_Compras);
        jPanel_Compras.setLayout(jPanel_ComprasLayout);
        jPanel_ComprasLayout.setHorizontalGroup(
            jPanel_ComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1301, Short.MAX_VALUE)
        );
        jPanel_ComprasLayout.setVerticalGroup(
            jPanel_ComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 583, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab6", jPanel_Compras);

        Button_Clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Clientes.png"))); // NOI18N
        Button_Clientes.setText("Clientes");
        Button_Clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_ClientesActionPerformed(evt);
            }
        });

        Button_Ventas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/compras.png"))); // NOI18N
        Button_Ventas.setText("Ventas");
        Button_Ventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_VentasActionPerformed(evt);
            }
        });

        Button_Compras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Carrito-de-compras.png"))); // NOI18N
        Button_Compras.setText("Compras");
        Button_Compras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_ComprasActionPerformed(evt);
            }
        });

        Button_Productos.setText("Productos");
        Button_Productos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_ProductosActionPerformed(evt);
            }
        });

        Button_Config.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Process-Accept.png"))); // NOI18N
        Button_Config.setText("Reportes");
        Button_Config.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_ConfigActionPerformed(evt);
            }
        });

        Button_Proveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/image-2018-03.png"))); // NOI18N
        Button_Proveedores.setText("Proovedores");
        Button_Proveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_ProveedoresActionPerformed(evt);
            }
        });

        jButton1.setText("jButton1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Button_Productos, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Button_Config, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Button_Clientes, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Button_Ventas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Button_Compras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button_Proveedores, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Button_Clientes, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Button_Ventas, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Button_Compras, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_Productos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_Config, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_Proveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void cargarDatos(int dato){
        switch(dato){
            case 0:
                p_c.cargarDatos();
                break;
            case 1:
                //prov.cargarDatos();
                break;
        }
    
    }
    private void Button_ClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_ClientesActionPerformed
        jTabbedPane1.setSelectedIndex(0);
        tab = 0;
        Button_Clientes.setEnabled(false);
        Button_Proveedores.setEnabled(true);
        Button_Compras.setEnabled(true);
        Button_Config.setEnabled(true);
        Button_Ventas.setEnabled(true);
        Button_Productos.setEnabled(true);
        cargarDatos(tab);
    }//GEN-LAST:event_Button_ClientesActionPerformed

    private void Button_ProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_ProductosActionPerformed
        jTabbedPane1.setSelectedIndex(2);
        tab = 2;
        Button_Clientes.setEnabled(true);
        Button_Proveedores.setEnabled(true);
        Button_Compras.setEnabled(true);
        Button_Config.setEnabled(true);
        Button_Ventas.setEnabled(true);
        Button_Productos.setEnabled(false);
        cargarDatos(tab);
    }//GEN-LAST:event_Button_ProductosActionPerformed

    private void Button_ConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_ConfigActionPerformed
         jTabbedPane1.setSelectedIndex(3);
        tab = 3;
        Button_Clientes.setEnabled(true);
        Button_Proveedores.setEnabled(true);
        Button_Compras.setEnabled(true);
        Button_Config.setEnabled(false);
        Button_Ventas.setEnabled(true);
        Button_Productos.setEnabled(true);
        cargarDatos(tab);          
    }//GEN-LAST:event_Button_ConfigActionPerformed

    private void Button_VentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_VentasActionPerformed
         jTabbedPane1.setSelectedIndex(4);
        tab = 4;
        Button_Clientes.setEnabled(true);
        Button_Proveedores.setEnabled(true);
        Button_Compras.setEnabled(true);
        Button_Config.setEnabled(true);
        Button_Ventas.setEnabled(false);
        Button_Productos.setEnabled(true);
        cargarDatos(tab);
    }//GEN-LAST:event_Button_VentasActionPerformed

    private void Button_ComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_ComprasActionPerformed
        jTabbedPane1.setSelectedIndex(5);
        tab = 5;
        Button_Clientes.setEnabled(true);
        Button_Proveedores.setEnabled(true);
        Button_Compras.setEnabled(false);
        Button_Config.setEnabled(true);
        Button_Ventas.setEnabled(true);
        Button_Productos.setEnabled(true);
        cargarDatos(tab);
    }//GEN-LAST:event_Button_ComprasActionPerformed

    private void Button_ProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_ProveedoresActionPerformed
        jTabbedPane1.setSelectedIndex(0);
        tab = 0;
        Button_Clientes.setEnabled(true);
        Button_Proveedores.setEnabled(false);
        Button_Compras.setEnabled(true);
        Button_Config.setEnabled(true);
        Button_Ventas.setEnabled(true);
        Button_Productos.setEnabled(true);
        cargarDatos(tab);
    }//GEN-LAST:event_Button_ProveedoresActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Clientes;
    private javax.swing.JButton Button_Compras;
    private javax.swing.JButton Button_Config;
    private javax.swing.JButton Button_Productos;
    private javax.swing.JButton Button_Proveedores;
    private javax.swing.JButton Button_Ventas;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel_C;
    private javax.swing.JPanel jPanel_Cliente;
    private javax.swing.JPanel jPanel_Compras;
    private javax.swing.JPanel jPanel_Productos;
    private javax.swing.JPanel jPanel_Proveedores;
    private javax.swing.JPanel jPanel_Ventas;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

}
